devsearch/urls.py
from django.contrib import admin
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    
    # paths for reset password
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
         name='reset_password'),
    
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name='password_reset_done'),
    
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="reset_password_confirm.html"),
         name='password_reset_confirm'),
    
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name='password_reset_complete')
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login/", views.loginUser, name="login"),
    path("register/", views.registerUser, name="register"),
    path("logout/", views.logoutUser, name="logout"),
    path("", views.profiles, name="profiles"),
    path("profile/<str:pk>", views.userProfile, name="user-profile"),
    path("account/", views.userAccount, name="account"),
    path("edit-account/", views.editAccount, name="edit-account"),
    path("create-skill", views.createSkill, name="create-skill"),
    path("update-skill/<str:pk>", views.updateSkill, name="update-skill"),
    path("delete-skill/<str:pk>", views.deleteSkill, name="delete-skill"),
    path("user-inbox/", views.userInbox, name="user-inbox"),
    path("user-message/<str:pk>/", views.viewUserMessage, name="user-message"),
    path("create-message/<str:pk>/", views.createMessage, name="create-message"),

]

projects/models.py
from django.db import models
from users.models import Profile

import uuid

class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title= models.CharField(max_length=255)
    description= models.TextField(null=True, blank=True, max_length=255)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, blank=True, null=True)
    source_link = models.CharField(max_length=2000, blank=True, null=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        return self.title    
    
    class Meta:
        ordering = ['-vote_ratio', "-vote_total", "title"] # order of projects depends on review 
    

    
    @property
    def imageURL(self):
        try:
            url = self.featured_image.url
        except:
            url = ''
        return url
    
    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset
    
    
    @property # write as a property becuase we want call without () just by name of function 
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value="up").count()
        totalVotes = reviews.count()
        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio
        self.save()
    



class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up vote'),
        ('down', 'Down vote'),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True, max_length=255)
    value = models.CharField(max_length=255, choices = VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        unique_together = [['owner', 'project']] # make sure every profile can leave one comment on th same project

    def __str__(self):
        return (self.value)
    

class Tag(models.Model):
    name = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=255, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    short_intro = models.CharField(max_length=255, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(blank=True, null=True, upload_to='profiles', default="profiles/default.jpg")
    social_github = models.CharField(max_length=255, blank=True, null=True)
    social_linkedin = models.CharField(max_length=255, blank=True, null=True)
    social_twitter = models.CharField(max_length=255, blank=True, null=True)
    social_youtube = models.CharField(max_length=255, blank=True, null=True)
    social_website = models.CharField(max_length=255, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        return str(self.username)
    
    @property
    def imageURL(self):
        try:
            url = self.profile_image.url
        except:
            url = ''
        return url
    
    
class Skill(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        return str(self.name)
    
    
class Message(models.Model):
    sender = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    receiver = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL, related_name="messages")
    name = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(max_length=255, blank=True, null=True)
    subject = models.CharField(max_length=255, blank=True, null=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    
    def __str__(self):
        return str(self.subject)
    
    
    class Meta:
        ordering = ["is_read", "-created"]
    

users/forms.py
from django.db.models import fields
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Skill, Message

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["first_name", "email", "username", "password1", "password2"]
        labels = {
            "first_name": "Name",
        }
    
    
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})
            
            
            
class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ["name", "email", "username", "location", "bio", 
                  "short_intro", "profile_image", "social_github", 
                  "social_linkedin", "social_twitter", "social_youtube", 
                  "social_website"
                ]
        
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})
            
            
            
class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = "__all__"
        exclude = ["owner"]
        
        
    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})
            
            
            
class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ["name", "email", "subject", "body"]
        
    
    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import CustomUserCreationForm, ProfileForm, SkillForm, MessageForm
from .utils import searchProfiles, paginationProfiles



def profiles(request):
    profiles, search_query = searchProfiles(request)
    
    custom_range, profiles = paginationProfiles(request, profiles, 3)
    
    context={
        "profiles": profiles,
        "search_query": search_query,
        "custom_range": custom_range
    }
    return render(request ,'users/profiles.html', context)



def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)
    skillsWithDesc = profile.skill_set.exclude(description__exact="")
    skillsWithoutDesc = profile.skill_set.filter(description="")
    context={
        "profile": profile,
        "skillsWithDesc":skillsWithDesc,
        "skillsWithoutDesc":skillsWithoutDesc
    }
    return render(request ,'users/user-profile.html', context)



def loginUser(request):
    page = "login"
    context = {
        "page": page
    }
    
    if request.user.is_authenticated:
        return redirect("profiles")
    
    if request.method == 'POST':
        username= request.POST['username'].lower()
        password= request.POST['password']
        
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request,"Username does not exist")
            
        user = authenticate(request, username=username, password=password) 
        
        if user is not None:
            login(request, user)
            return redirect(request.GET['next'] if 'next' in request.GET else 'account')
        else:
            messages.error(request,"Username or password does not exist")
            
            
    return render(request, 'users/login_register.html', context)



def logoutUser(request):
    logout(request)
    messages.success(request,"User was successfully logged out")
    return redirect('login')



def registerUser(request):
    page="register"
    form = CustomUserCreationForm()
    
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False) # we put commit = False to create a instance from user to edit and login
            user.username = user.username.lower()
            user.save()
            
            messages.success(request,"User account was successfully created")
            
            login(request, user)
            return redirect("edit-account")
        
        else:
            messages.error(request,"Somthing went wrong during registration")

    
    context = {
        "page": page,
        "form": form
    }
    return render(request, 'users/login_register.html', context)



@login_required(login_url="login")
def userAccount(request):
    profile = request.user.profile
    allSkills = profile.skill_set.all()
    context = {
        "profile": profile,
        "allSkills":allSkills,
    }
    return render(request, 'users/account.html', context)
    
    

@login_required(login_url="login")
def editAccount(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            
            return redirect("account")
    
    context = {
        "form": form
    }
    return render(request, 'users/profile_form.html', context)




@login_required(login_url="login")
def createSkill(request):
    profile = request.user.profile
    form = SkillForm()
    
    if request.method == "POST":
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit= False)
            skill.owner = profile
            skill.save()
            messages.success(request,"Skill was created successfully")

            return redirect("account")
    
    context = {
        "form": form
    }
    return render(request, 'users/skill_form.html', context)




@login_required(login_url="login")
def updateSkill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    form = SkillForm(instance=skill)
    
    if request.method == "POST":
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            messages.success(request,"Skill was updated successfully")

            return redirect("account")
    
    context = {
        "form": form
    }
    return render(request, 'users/skill_form.html', context)



def deleteSkill(request, pk):
    
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    if request.method == "POST":
        skill.delete()
        messages.success(request,"Skill was deleted successfully")
        return redirect("account")
    context = {
        "object": skill
    }
    return render(request, 'delete_confirm_template.html', context)



@login_required(login_url="login")
def userInbox(request):
    profile = request.user.profile # get user profile 
    profileMessages =  profile.messages.all() # get all user messages 
    unReadMessages = profileMessages.filter(is_read=False).count() # get all unread messages
    context = {
        "profileMessages": profileMessages,
        "unReadMessages": unReadMessages
    }
    return render(request, 'users/user_inbox.html', context)


@login_required(login_url="login")
def viewUserMessage(request, pk):
    profile = request.user.profile 
    message = profile.messages.get(id=pk)
    if message.is_read == False: # mark message as read
        message.is_read = True
        message.save()
    context = {
        "message": message
    }
    return render(request, 'users/user_message.html', context)



def createMessage(request, pk):
    receiver = Profile.objects.get(id=pk)
    form = MessageForm()
    
    try:
        sender = request.user.profile
    except:
        sender = None
        
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit= False)
            message.sender = sender
            message.receiver = receiver
            
            if sender:
                message.name = sender.name
                message.email = sender.email
                
            message.save()
            messages.success(request, "Your message was successfully sent!!")
            return redirect('user-profile', pk=receiver.id)
            
    
    context = {
        "receiver": receiver,
        "form": form
    }
    return render(request, 'users/message_form.html', context)

users/templates/users/account.html
{% extends "main.html" %} 

{% block content %}

<main class="settingsPage profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"
              ><i class="im im-edit"></i> Edit</a
            >
            <img
              class="avatar avatar--xl dev__avatar"
              src="{{ profile.imageURL }}"
            />
            <h2 class="dev__name">{{profile.name}}</h2>
            <p class="dev__title">
              {{profile.short_intro}}
            </p>
            <p class="dev__location">{{profile.location}}</p>
             <ul class="dev__social">
              {% if profile.social_github %}
              <li>
                <a
                  title="Github"
                  href="{{ profile.social_github }}"
                  target="_blank"
                  ><i class="im im-github"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_twitter %}
              <li>
                <a
                  title="Twitter"
                  href="{{profile.social_twitter}}"
                  target="_blank"
                  ><i class="im im-twitter"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_linkedin%}
              <li>
                <a title="LinkedIn" href="{{profile.linkedin}}" target="_blank"
                  ><i class="im im-linkedin"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_website %}
              <li>
                <a
                  title="Personal Website"
                  href="{{profile.social_website}}"
                  target="_blank"
                  ><i class="im im-globe"></i
                ></a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">
            {{profile.bio}}
          </p>
        </div>
        <div class="settings">
          <h3 class="settings__title">Skills</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"
            ><i class="im im-plus"></i> Add Skill</a
          >
        </div>

        <table class="settings__table">
            {% for skill in allSkills %}
          <tr>
            <td class="settings__tableInfo">
              <h4>{{skill}}</h4>
              <p>
                {{skill.description}}
              </p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"
                ><i class="im im-edit"></i> Edit</a
              >
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}?next=/account"
                ><i class="im im-x-mark-circle-o"></i> Delete</a
              >
            </td>
          </tr>
          {% endfor %}
        </table>

        <div class="settings">
          <h3 class="settings__title">Projects</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"
            ><i class="im im-plus"></i> Add Project</a
          >
        </div>

        <table class="settings__table">
        {% for project in profile.project_set.all %}
          <tr>
            <td class="settings__thumbnail">
              <a href="{% url 'project' project.id %}"
                ><img src="{{ project.imageURL }}" alt="Project Thumbnail"
              /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="{% url 'project' project.id %}">{{project.title}}</a>
              <p>
                {{project.description|slice:"150"}}
              </p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"
                ><i class="im im-edit"></i> Edit</a
              >
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' project.id %}?next=/account"
                ><i class="im im-x-mark-circle-o"></i> Delete</a
              >
            </td>
          </tr>
        {% endfor %}
        </table>
      </div>
    </div>
  </div>
</main>

{% endblock content %}

users/templates/users/login_register.html
{% extends "main.html" %} 

{% load static %} 

{% block content %} 

{% if page == "register" %}

   <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/icon.svg' %}" alt="icon" />
          </a>
          <h3>Account SignUp</h3>
          <p>Create a new developer account</p>
        </div>

        <form method="post" action="{% url 'register' %}" class="form auth__form">
          {% csrf_token %}
          <!-- Input:Text -->
          
          {% for field in form %}
          <div class="form__field">
            <label for="formInput#confirm-password">{{field.label}}</label>
              {{ field }}
              {% for error in field.errors %}
                <p style="color:red" >{{error}}</p>
              {% endfor %}
          </div>

          {% endfor %}
          <div class="auth__actions">
            <input
              class="btn btn--sub btn--lg"
              type="submit"
              value="Sign Up"
            />
          </div>
        </form>
        <div class="auth__alternative">
          <p>Already have an Account?</p>
          <a href="{% url 'login' %}">Log In</a>
        </div>
      </div>
    </div>

{% else %}
<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Account Login</h3>
      <p>Hello Developer, Welcome Back!</p>
    </div>

    <form action="" method="POST" class="form auth__form">
      {% csrf_token %}
      <!-- Input:Username -->
      <div class="form__field">
        <label for="formInput#text">Username: </label>
        <input
          class="input input--text"
          id="formInput#text"
          type="text"
          name="username"
          placeholder="Enter your username..."
        />
      </div>

      <!-- Input:Password -->
      <div class="form__field">
        <label for="formInput#password">Password: </label>
        <input
          class="input input--password"
          id="formInput#passowrd"
          type="password"
          name="password"
          placeholder="••••••••"
        />
      </div>
      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
        <a href="{% url 'reset_password' %}">Forget Password?</a>
      </div>
    </form>

    <div class="auth__alternative">
      <p>Don’t have an Account?</p>
      <a href="{% url 'register' %}">Sign Up</a>
    </div>
  </div>
</div>
{% endif %} {% endblock content %}

users/templates/users/message_form.html
{% extends "main.html"%} {% block content %}

<!-- Main Section -->
<main class="formPage my-xl">
  <div class="content-box">
    <div class="formWrapper">
      <a class="backButton" href="{% url 'user-profile' receiver.id %}"
        ><i class="im im-angle-left"></i
      ></a>
      <br />

      <form class="form" method="POST">
        {% csrf_token %} {% if request.user.is_authenticated == False %}
        <div class="form__field">
          <label for="formInput#text">{{form.name.label}}</label>
          {{form.name}}
        </div>

        <div class="form__field">
          <label for="formInput#text">{{form.email.label}}</label>
          {{form.email}}
        </div>
        {% endif %}

        <div class="form__field">
          <label for="formInput#text">{{form.subject.label}}</label>
          {{form.subject}}
        </div>

        <div class="form__field">
          <label for="formInput#text">{{form.body.label}}</label>
          {{form.body}}
        </div>
        <input
          class="btn btn--sub btn--lg my-md"
          type="submit"
          value="Submit"
        />
      </form>
    </div>
  </div>
</main>

{% endblock content %}

users/templates/users/profile_form.html
{% extends "main.html"%} 

{% block content %}

<!-- Main Section -->
<main class="formPage my-xl">
  <div class="content-box">
    <div class="formWrapper">
      <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
      <br />

      <form class="form"   method="POST" action="{% url 'edit-account' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- Input:Text -->
        {% for field in form %}
        <div class="form__field">
          <label for="formInput#text">{{field.label}}</label>
            {{field}}
        </div>
        {% endfor %}

        <input
          class="btn btn--sub btn--lg my-md"
          type="submit"
          value="Submit"
        />
      </form>
    </div>
  </div>
</main>

{% endblock content %}

users/templates/users/skill_form.html
{% extends "main.html" %} 

{% block content %}

<!-- Main Section -->
<main class="formPage my-xl">
  <div class="content-box">
    <div class="formWrapper">
      <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
      <br />

      <form class="form" method="POST" action="">
        {% csrf_token %}
        <!-- Input:Text -->

        {% for field in form %}
        <div class="form__field">
          <label for="formInput#text">{{field.label}}</label>
            {{field}}
        </div>
        {% endfor %}

        <input
          class="btn btn--sub btn--lg my-md"
          type="submit"
          value="Submit"
        />
      </form>
    </div>
  </div>
</main>

{% endblock content %}

users/templates/users/user-profile.html
{% extends "main.html"%} {% block content %}
<!-- Main Section -->
<main class="profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <img
              class="avatar avatar--xl"
              src="{{profile.imageURL}}"
            />
            <h2 class="dev__name">{{profile.name}}</h2>
            <p class="dev__title">{{profile.short_intro|slice:"60"}}</p>
            <p class="dev__location">{{profile.location}}</p>
            <ul class="dev__social">
              {% if profile.social_github %}
              <li>
                <a
                  title="Github"
                  href="{{ profile.social_github }}"
                  target="_blank"
                  ><i class="im im-github"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_twitter %}
              <li>
                <a
                  title="Twitter"
                  href="{{profile.social_twitter}}"
                  target="_blank"
                  ><i class="im im-twitter"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_linkedin%}
              <li>
                <a title="LinkedIn" href="{{profile.linkedin}}" target="_blank"
                  ><i class="im im-linkedin"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_website %}
              <li>
                <a
                  title="Personal Website"
                  href="{{profile.social_website}}"
                  target="_blank"
                  ><i class="im im-globe"></i
                ></a>
              </li>
              {% endif %}
            </ul>
            {% if request.user.profile.id != profile.id %}
            <a
              href="{% url 'create-message' profile.id %}"
              class="btn btn--sub btn--lg"
              >Send Message
            </a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">{{profile.bio}}</p>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Skills</h3>
          <div class="devInfo__skills">
            {% for skill in skillsWithDesc %}
            <div class="devSkill">
              <h4 class="devSkill__title">{{skill.name}}</h4>
              <p class="devSkill__info">{{skill.description}}</p>
            </div>
            {% endfor %}

            <h3 class="devInfo__subtitle">Other Skills</h3>
            <div class="devInfo__otherSkills">
              {% for skill in skillsWithoutDesc %}
              <span class="tag tag--pill tag--sub tag--lg">
                <small>{{skill}}</small>
              </span>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Projects</h3>
          <div class="grid grid--two">
            {% for project in profile.project_set.all %}
            <div class="column">
              <div class="card project">
                <a href="{% url 'project' project.id %}" class="project">
                  <img
                    class="project__thumbnail"
                    src="{{project.imageURL}}"
                    alt="project thumbnail"
                  />
                  <div class="card__body">
                    <h3 class="project__title">{{project.title}}</h3>
                    <p>
                      <a
                        class="project__author"
                        href="{% url 'user-profile' project.owner.id %}"
                        >By {{project.owner}}</a
                      >
                    </p>
                    <p class="project--rating">
                      <span style="font-weight: bold"
                        >{{project.vote_ratio}}%</span
                      >
                      Postitive Feedback ({{project.vote_total}} Votes)
                    </p>
                    <div class="project__tags">
                      {% for tag in project.tags.all %}
                      <span class="tag tag--pill tag--main">
                        <small>{{tag}}</small>
                      </span>
                      {% endfor %}
                    </div>
                  </div>
                </a>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}